In [1]:
import requests
import bs4 as bs
import pandas as pd
import numpy as np
import re
import json

In [90]:
data = pd.read_csv('data_populated_all_fixed_8000.csv', index_col=0)
data_4000 = pd.read_csv('data_populated_all.csv', index_col=0)

In [91]:
data.head()

,address,link,long,lat,property_type,property_costs,total_area,number_of_units,year_built,parking_spots,volume_rate,green_rating,developer_company,property_management_company
0,汤臣一品,https://shanghai.anjuke.com/community/view/8,31.238608,121.508381,公寓,15.00元/平米/月,115000m²,220户,2006年,458,5.97,40%(高),汤臣海景花园（上海浦东新区）有限公司,晶华物业有限公司
1,中粮海景壹号,https://shanghai.anjuke.com/community/view/218807,31.236882,121.510280,公寓,12.00元/平米/月,70000m²,311户,2010年,600,4,51%(高),上海鹏利置业发展有限公司,上海高力国际物业服务有限公司
2,陆家嘴锦绣前城,https://shanghai.anjuke.com/community/view/725250,31.201611,121.542311,公寓,1.00元/平米/月,暂无数据,暂无数据,2016年,200,1.8,40%(高),上海陆家嘴（集团）有限公司,上海市陆家嘴物业管理有限公司
3,张江一村,https://shanghai.anjuke.com/community/view/13947,31.212369,121.619192,公寓,0.40元/平米/月,暂无数据,暂无数据,1995年,300个,1.8,32%(一般),暂无数据,暂无数据
4,长岛花苑,https://shanghai.anjuke.com/community/view/2679,31.270386,121.609057,公寓,1.00元/平米/月,23000m²,2034户,1993年,1000,1.2,35%(一般),上海浦东伟业房地产开发总公司,上海洋泾物业

In [92]:
data_4000.head()

,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,Unnamed: 0.1.1.1.1,Unnamed: 0.1.1.1.1.1,0,link,long,la,type,Property type,Property costs,Total area,Number of units,Year built,Parking spots,Volume rate,Green rating,Developer Company,Property management company
0,0,0,0,0,0,汤臣一品,https://shanghai.anjuke.com/community/view/8,31.238608,121.508381,2.295401e-314,公寓,15.00元/平米/月,141894m²,220户,2006年,200,5.97,40%(高),汤臣海景花园（上海浦东新区）有限公司,晶华物业有限公司
1,1,1,1,1,1,中粮海景壹号,https://shanghai.anjuke.com/community/view/218807,31.236882,121.510280,2.295413e-314,公寓,12.00元/平米/月,116605m²,317户,2010年,200,4,51%(高),上海鹏利置业发展有限公司,上海高力国际物业服务有限公司
2,2,2,2,2,2,陆家嘴锦绣前城,https://shanghai.anjuke.com/community/view/725250,31.201611,121.542311,2.249721e-314,公寓,1.00元/平米/月,暂无数据,暂无数据,2016年,200,1.8,40%(高),上海陆家嘴（集团）有限公司,上海市陆家嘴物业管理有限公司
3,3,3,3,3,3,张江一村,https://shanghai.anjuke.com/community/view/13947,31.212369,121.619192,2.295401e-314,公寓,0.40元/平米/月,暂无数据,暂无数据,1995年,300个,1.8,32%(一般),暂无数据,暂无数据
4,4,4,4,4,4,长岛花苑,https://shanghai.anjuke.com/community/view/2679,31.270386,121.609057,2.295401e-314,公寓,1.00元/平米/月,23000m²,2034户,1993年,1000,1.2,35%(一般),上海浦东伟业房地产开发总公司,上海洋泾物业

In [93]:
# columns_to_drop = []
# for i in [2015, 2016, 2017]:
#     start = 1
#     if i == 2015:
#         start = 4
#     for j in range(start, 13):
#         j_str = str(j)
#         if j < 10:
#             j_str = '0' + j_str 
#         columns_to_drop.append(str(i) + j_str)
# columns_to_drop += ['201801', '201802', '201803']
# columns_to_drop

columns_to_drop = ['Unnamed: 0.1', 'Unnamed: 0.1.1', 'Unnamed: 0.1.1.1', 'Unnamed: 0.1.1.1.1', 'Unnamed: 0.1.1.1.1.1']
columns_to_drop.append('type')
columns_to_drop

['Unnamed: 0.1',
 'Unnamed: 0.1.1',
 'Unnamed: 0.1.1.1',
 'Unnamed: 0.1.1.1.1',
 'Unnamed: 0.1.1.1.1.1',
 'type']

In [94]:
data_4000 = data_4000.drop(columns_to_drop, axis=1)

In [95]:
data = data[4000:8001]
data.shape

(4001, 14)

In [99]:
data_4000 = data_4000[0:4001]
data_4000.shape

(4001, 14)

In [100]:
data_4000_renamed = data_4000.rename(columns=dict(zip(data_4000.columns, data.columns)))

In [101]:
data_combined = pd.concat([data_4000_renamed, data])

In [102]:
data_combined.shape

(8002, 14)

In [108]:
data_combined[0:8001].to_csv('data_populated_0_8000.csv')